Universe                = vanilla
Executable              = mini_test_bnn_neat.sh
Arguments               = 
Environment             = "PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True"

Requirements            = (Target.GPUSlot)
Request_GPUs            = 1
Initialdir              = /scratch/cluster/dylantw/Risto/init
Output                  = mini_test_bnn_neat.out
Error                   = mini_test_bnn_neat.err
Log                     = mini_test_bnn_neat.log

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = test_bnn_neat_mini.py, mini_test_bnn_neat.sh, bnn.py, mini-config-feedforward

# UTCS-specific attributes
+Group                  = "UNDER"
+Project                = "AI_ROBOTICS"
+ProjectDescription     = "BNN-NEAT Testing"
+GPUJob = true

request_memory = 60000
request_cpus   = 1

Queue

