Universe                = vanilla
Executable              = /lusr/opt/miniconda/envs/pytorch-cuda/bin/python3
Arguments               = test_bayesian_nn.py
Environment             = "PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True"

Requirements            = (Target.GPUSlot)
Request_GPUs            = 1
Initialdir              = /scratch/cluster/dylantw/Risto/init
Output                  = test_bayesian_nn.out
Error                   = test_bayesian_nn.err
Log                     = test_bayesian_nn.log

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = bnn.py, evolve_neat.py, test_bayesian_nn.py

# UTCS-specific attributes
+Group                  = "UNDER"
+Project                = "AI_ROBOTICS"
+ProjectDescription     = "BNN Testing"
+GPUJob = true

request_memory = 60000
request_cpus   = 1

Queue

