Universe                = vanilla
Executable              = /lusr/opt/miniconda/envs/pytorch-cuda/bin/python3
Arguments               = test_neat.py
Environment             = "PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True"

Requirements            = (Target.GPUSlot)
Request_GPUs            = 1
Initialdir              = /scratch/cluster/dylantw/Risto/init
Output                  = test_neat2.out
Error                   = test_neat2.err
Log                     = test_neat2.log

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = test_neat.py, config-feedforward

# UTCS-specific attributes
+Group                  = "UNDER"
+Project                = "AI_ROBOTICS"
+ProjectDescription     = "BNN-NEAT Testing"
+GPUJob = true

request_memory = 60000
request_cpus   = 1

Queue

