Universe                = vanilla
Executable              = test_bnn_neat_full.sh
Arguments               = 
Environment             = "PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True"

Requirements            = (Target.GPUSlot)
Request_GPUs            = 1
Initialdir              = /scratch/cluster/dylantw/Risto/init
Output                  = test_bnn_neat_full.out
Error                   = test_bnn_neat_full.err
Log                     = test_bnn_neat_full.log

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = test_bnn_neat_full.py, test_bnn_neat_full.sh, bnn.py, config-feedforward

# UTCS-specific attributes
+Group                  = "UNDER"
+Project                = "AI_ROBOTICS"
+ProjectDescription     = "BNN-NEAT Testing"
+GPUJob = true

request_memory = 60000
request_cpus   = 1

Queue

