from emotion_rate import emotion_rating, ethical_scores, ground_truth
model = "gpt-4o-mini"


def update_bnn_history(response, agent, bnn_history, max_length, temperature, top_p, global_counter, ethics_score=0, death=False):
    """
    This function captures and stores information about a prompt-response interaction between an agent and the AI.
    It retrieves both the text embeddings and emotional scores for the prompt and response, appending this data to
    the Bayesian Neural Network (BNN) history for future use in decision-making processes.

    Parameters:
    ----------
    response : dict
        The response generated by the AI (typically an OpenAI API response object), which includes both
        the content and metadata for the generated text.

    agent : str
        Identifier for the agent (e.g., "strong" or "weak") which is used to tailor the emotion rating
        for the prompt or response.

    bnn_history : list
        A list that stores the history of interactions, including embeddings, text, and emotional/ethical scores.
        This history can later be used as input to a Bayesian Neural Network (BNN) for decision-making.

    Returns:
    -------
    bnn_history
        The function modifies the `bnn_history` list in place by appending the prompt-response pair along
        with their respective embeddings and emotional/ethical scores.

    Notes:
    ------
    - This function interacts with an emotion rating function `emotion_rating()` to calculate the emotional or
      ethical dimension of the prompt and response based on the agent's perspective.
    - OpenAI's embeddings API is used to generate embeddings for both the prompt and response text.
    - Ensure that `bnn_history` is initialized as an empty list or carries the previous conversation history
      before calling this function.

    Example Usage:
    --------------
    bnn_history = bnn_history(prompt="What should we do next?", response=api_response, first_prompt=True,
                agent="weak", bnn_history=interaction_history)
    """

    if agent in ["Strong", "Weak"]:
        response_embedding = client.embeddings.create(
            input=response,
            model="text-embedding-3-small"
        ).data[0].embedding
        response_embedding.extend([-1] * 1536 * 4)
        #response_emotion_score = emotion_rating(response, agent, max_length, 0.1, top_p)
        bnn_history.append({
            "agent": agent,
            "response": response,
            "response_embedding": response_embedding,
            "emotional_and_ethical_score": ethics_score,
            "environment_danger_score": 0,
            "survived": 1
        })
        #print("Response Embedding Length (Agent): ", len(response_embedding))

    elif agent == "Storyteller":
        intro, choices = extract_choices_and_intro(response)
        response_embedding = []
        intro_embedding = client.embeddings.create(
            input=intro,
            model="text-embedding-3-small"
        ).data[0].embedding
        response_embedding.extend(intro_embedding)
        #print("CHOICE_LIST: ", choices)
        for choice in choices:
            choice_embedding = client.embeddings.create(
                input=choice,
                model="text-embedding-3-small"
            ).data[0].embedding
            response_embedding.extend(choice_embedding)

        #print(len(response_embedding))

        if death:
            response_embedding.extend([-1] * 1536 * 4)
            if len(bnn_history) >= 1:
                bnn_history[-1]["survived"] = 0
                #bnn_history[-2]["survived"] = 0
            environment_danger_score = emotion_rating(response, agent, max_length, 0.1, top_p)
            bnn_history.append({
                "id": global_counter,
                "agent": agent,
                "response": response,
                "response_embedding": response_embedding,
                "emotional_and_ethical_score": 0,
                "environment_danger_score": environment_danger_score,
                "survived": -1
            })
        else:
            environment_danger_score = emotion_rating(response, agent, max_length, 0.1, top_p)
            bnn_history.append({
                "id": global_counter,
                "agent": agent,
                "response": response,
                "response_embedding": response_embedding,
                "emotional_and_ethical_score": 0,
                "environment_danger_score": environment_danger_score,
                "survived": -1
            })
        #print("Response Embedding Length (Storyteller): ", len(response_embedding))

    elif agent == "Power":
        response_embedding = client.embeddings.create(
            input=response,
            model="text-embedding-3-small"
        ).data[0].embedding
        response_embedding.extend([-1] * 1536 * 4)
        bnn_history.append({
                "agent": agent,
                "response": response,
                "response_embedding": response_embedding,
                "emotional_and_ethical_score": 0,
                "environment_danger_score": 0,
                "survived": 1
            })

    #print(bnn_history)

    return bnn_history

